version: '3'

services:
  clash-proxy:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - "8601:8501"  # Streamlit UI
      - "8600:8000"  # API